spring:
  profiles:
    active: dev
logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
jwt:
  secret: s3BTt6uIdU6/99xZQYfOQoh4cRrJyZIXSbrmq+4nDog

---

spring:
    profiles:
        active: release
jwt:
  secret: s3BTt6uIdU6/99xZQYfOQoh4cRrJyZIXSbrmq+4nDog