jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: pilyoga

jwt:
  secret: s3BTt6uIdU6/99xZQYfOQoh4cRrJyZIXSbrmq+4nDog

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**

db-config:
  host: getx-mysql-test.cebci2gmpvew.ap-northeast-2.rds.amazonaws.com
  port: 3306
  name: fitnessTeachersDB
  username: jino
  password: ENC(1HDF9pxjaOsYt6VKXmIMSg==)

spring:
  datasource:
    url: jdbc:mysql://${db-config.host}:${db-config.port}/${db-config.name}
    username: ${db-config.username}
    password: ${db-config.password}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true