spring:
  profiles:
    active: dev
logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
jwt:
  secret: s3BTt6uIdU6/99xZQYfOQoh4cRrJyZIXSbrmq+4nDog

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**