logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL : DEBUG
    org.hibernate.orm.jdbc.extract: TRACE
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: pilyotesttesttesttesttesttesttesttesttesttesttespilyotesttesttesttesttesttesttesttesttesttesttestt

spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 597656425443-594gqbrji63li3oivojsq6uhb3275u10.apps.googleusercontent.com
            clientSecret: enc(eSitLrVFeIyJMUl+Epoy5UNKmuB5Mz6a0DvwJ9rG/hoXeQFllbsjx9SpTYvUlxQj)
            scope:
              - email
              - profile

          naver:
            clientId: 2aIpUgp68uEYugBfJ44f
            clientSecret: sZ0wlp6QN8
            authorizationGrantType: authorization_code
            clientAuthenticationMethod : client_secret_post
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - mobile
              - profile_image
            client-name: Naver

          kakao:
            clientId: ea6371bfabae8491821c0c3d6464591a
            clientSecret: enc(jnR0Jw+1jLdOwYoX5cNECtdrtO3yP0sVtwIUhCBHHDr2Ez67XngXsKL3H2nytw9q)
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorizationGrantType: authorization_code
            clientAuthenticationMethod : client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - profile_email
            client-name: Kakao

        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            userNameAttribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            userNameAttribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정
