jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: pilyoga

db-config:
  host: getx-mysql-test.cebci2gmpvew.ap-northeast-2.rds.amazonaws.com
  port: 3306
  name: fitnessTeachersDB
  username: jino
  password: ENC(1HDF9pxjaOsYt6VKXmIMSg==)

spring:
  datasource:
    url: jdbc:mysql://${db-config.host}:${db-config.port}/${db-config.name}
    username: ${db-config.username}
    password: ${db-config.password}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true