jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: pilyoga
spring:
  datasource:
    url: jdbc:mysql://getx-mysql-test.cebci2gmpvew.ap-northeast-2.rds.amazonaws.com:3306/fitnessTeachersDB
    username: jino
    password: ENC(1HDF9pxjaOsYt6VKXmIMSg==)
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true